### ISSUE TITLE
Allow submitting kwargs to the scipy.optimize.minimize function

### ISSUE THREAD

**Issue by Doggie52** [matthewgilbert/erc#2]
Thanks for a great module!

Would really appreciate it if it was possible to pass kwargs into `scipy.optimize.minimize` from the method, allowing for such things as setting a timeout (as described in https://stackoverflow.com/a/24827245/2449750, you need to pass the `callback` kwarg).

**Comment by matthewgilbert** [comment]
You can pass in kwargs via the `option` parameter, is there something this doesn't support?

**Comment by Doggie52** [comment]
`option` passes in kwargs into the solver - there are arguments to the `minimize` function (such as `callback`) which are not passed via the `option` dict.

Snapshot from the [docs](https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.minimize.html):

![image](https://user-images.githubusercontent.com/4928988/155775444-7392c3ec-2e4e-441e-afa5-d9c985995ee1.png)

**Comment by matthewgilbert** [comment]
Ahh I see. Sure happy to take a PR on this

**Comment by Doggie52** [comment]
Great, yeah, I'll send something over in the next few days
